---
- name: Check if iterm2 is installed
  homebrew_cask:
    name: "iterm2"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
    
- name: Get current Solarized package
  get_url: 
    url: "http://ethanschoonover.com/solarized/files/solarized.zip" 
    dest: "~/Downloads/"

- name: Cloning fonts
  git:
    repo: "https://github.com/powerline/fonts"
    dest: "~/.config/powerlinefonts"
    accept_hostkey: yes
  register: fontCloned
  become: no

- name: Install Fonts
  shell: ~/.config/powerlinefonts/install.sh 
  args: 
    chdir: '~/.config/powerlinefonts'
  when: fontCloned
  become: no

- name: iTerm custom settings file
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/setup_terminal/files"

- name: Installing zsh package
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh

- name: Installing oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "~/.oh-my-zsh"
    update: yes
  when: install_oh_my_zsh
