---
dotfiles_repo: "https://github.com/DemisR/dotfiles.git"
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: "~/Documents/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .zshrc
  - '.gitignore_global'
  - .inputrc
  - .vimrc
  - .gitconfig
  - .functions
  - .aliases
  - .vim
  - .osx
