---
bin_dir: /usr/local/bin
atom_upgrade_all: False
atom_packages:
  - language-ansible
  - atom-beautify
  - block-comment
  - file-icons
  - git-history
  - git-log
  - git-projects
  - git-plus
  - language-generic-config
  - language-nagios
  - merge-conflicts
  - open-recent
  - markdown-writer
  - pigments
  - project-manager
  - qolor

vscode_packages:
  - DavidAnson.vscode-markdownlint
  - DotJoshJohnson.xml
  - DougFinke.vscode-pandoc
  - EditorConfig.EditorConfig
  - HookyQR.beautify
  - PKief.material-icon-theme
  - PeterJausovec.vscode-docker
  - akamud.vscode-theme-onedark
  - donjayamanne.githistory
  - donjayamanne.python
  - emilast.LogFileHighlighter
  - file-icons.file-icons
  - haaaad.ansible
  - jasonn-porch.gitlab-mr
  - jebbs.plantuml
  - jgsqware.gitlab-ci-templates
  - lukehoban.Go
  - magicstack.MagicPython
  - mdickin.markdown-shortcuts
  - mrmlnc.vscode-apache
  - ms-vscode.PowerShell
  - redhat.vscode-yaml
  - shanoor.vscode-nginx
  - spywhere.guides
  - tht13.python
  - wayou.vscode-todo-highlight
  - wholroyd.jinja
  - yzane.markdown-pdf